### ISSUE TITLE
Is the max sampling rate really 100Hz ?

### ISSUE THREAD

**Issue by xiechuanyu** [pervasive-systems/eSense-Android-Library#1]
Hi, I have some problem when sampling accelerometer and gyroscope data.
I have use **manager.registerSensorListener(eSenseSensorListener, 100)** to set my sampling rate to 100Hz, and I also use **setAdvertisementAndConnectiontInterval(1000, 2000, 20,80)** set the minimum connection interval to be 20ms with the maximum connection interval to be 80ms . But I still receive the sensor data slower than the 100Hz rate. 

For example, I record the sensor data for 37s, there should be 3700 lines of data reveived from the method **onSensorChanged(ESenseEvent evt)**. But I count how many times this method is triggered, it is roughly 2550. I try several time, but it is still the same.

Is this a normal phenomenon?

**Comment by alessandro-montanari** [comment]
The sampling rate is really dependent on the BLE communication so it's difficult to get the exact value you set (e.g. 100Hz). However, with the devices we have tested we were able to get very close, e.g. 97-98Hz on average. Keep in mind that if you play music the rate will be lower.

Try to set the connection interval to 20ms and 40ms and then disconnect and re-connect the eSense again. This way the eSense will use the new values. Consider that the connection interval is only a recommendation from eSense to the host but the host can ignore that, hence resulting in a lower data rate.
